version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: tpc_postgres
    environment:
      POSTGRES_USER: tpc_user
      POSTGRES_PASSWORD: tpc_password
      POSTGRES_DB: tpc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tpc_user -d tpc_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: tpc_postgres_data 